insert into category (name) values ('Clothing/Shoe/Accessory Stores');
insert into category (name) values ('Major Banks');
insert into category (name) values ('Commercial Banks');
insert into category (name) values ('Hotels/Resorts');
insert into category (name) values ('Real Estate Investment Trusts');
insert into category (name) values ('EDP Services');
insert into category (name) values ('Other Consumer Services');
insert into category (name) values ('Biotechnology: In Vitro & In Vivo Diagnostic Substances');
insert into category (name) values ('n/a');
insert into category (name) values ('Major Banks');
insert into category (name) values ('Major Banks');
insert into category (name) values ('Property-Casualty Insurers');
insert into category (name) values ('Life Insurance');
insert into category (name) values ('Auto Parts:O.E.M.');
insert into category (name) values ('Hospital/Nursing Management');
insert into category (name) values ('n/a');
insert into category (name) values ('n/a');
insert into category (name) values ('Industrial Machinery/Components');
insert into category (name) values ('Real Estate');
insert into category (name) values ('Biotechnology: Laboratory Analytical Instruments');
insert into category (name) values ('Major Pharmaceuticals');
insert into category (name) values ('Construction/Ag Equipment/Trucks');
insert into category (name) values ('Packaged Foods');
insert into category (name) values ('Major Banks');
insert into category (name) values ('Professional Services');
insert into category (name) values ('Industrial Machinery/Components');
insert into category (name) values ('Biotechnology: Commercial Physical & Biological Resarch');
insert into category (name) values ('n/a');
insert into category (name) values ('Office Equipment/Supplies/Services');
insert into category (name) values ('Hotels/Resorts');
insert into category (name) values ('Telecommunications Equipment');
insert into category (name) values ('n/a');
insert into category (name) values ('Business Services');
insert into category (name) values ('EDP Services');
insert into category (name) values ('Business Services');
insert into category (name) values ('Major Banks');
insert into category (name) values ('Metal Fabrications');
insert into category (name) values ('Major Pharmaceuticals');
insert into category (name) values ('Major Pharmaceuticals');
insert into category (name) values ('Oil Refining/Marketing');
insert into category (name) values ('Metal Fabrications');
insert into category (name) values ('n/a');
insert into category (name) values ('Television Services');
insert into category (name) values ('Major Banks');
insert into category (name) values ('Savings Institutions');
insert into category (name) values ('Railroads');
insert into category (name) values ('Professional Services');
insert into category (name) values ('Oil & Gas Production');
insert into category (name) values ('Other Specialty Stores');
insert into category (name) values ('Finance: Consumer Services');
