insert into city (name, country_id) values ('Miyako', 6);
insert into city (name, country_id) values ('Três Rios', 2);
insert into city (name, country_id) values ('San Pedro', 7);
insert into city (name, country_id) values ('Czarna', 10);
insert into city (name, country_id) values ('Qui Nhon', 1);
insert into city (name, country_id) values ('Aroroy', 5);
insert into city (name, country_id) values ('Tlumach', 18);
insert into city (name, country_id) values ('Gexi', 7);
insert into city (name, country_id) values ('Xiashitai', 4);
insert into city (name, country_id) values ('Viçosa', 11);
insert into city (name, country_id) values ('Shah Alam', 2);
insert into city (name, country_id) values ('Lyski', 20);
insert into city (name, country_id) values ('Proástion', 18);
insert into city (name, country_id) values ('Shin’ichi', 4);
insert into city (name, country_id) values ('Jiaohu', 7);
insert into city (name, country_id) values ('Kaduseeng', 6);
insert into city (name, country_id) values ('Malawa', 13);
insert into city (name, country_id) values ('Yangxiang', 16);
insert into city (name, country_id) values ('Pégeia', 10);
insert into city (name, country_id) values ('Ait Ali', 9);
insert into city (name, country_id) values ('Shushicë', 11);
insert into city (name, country_id) values ('Gambēla', 17);
insert into city (name, country_id) values ('Korhogo', 15);
insert into city (name, country_id) values ('Irkutsk', 9);
insert into city (name, country_id) values ('Peresvet', 19);
insert into city (name, country_id) values ('Pinglin', 14);
insert into city (name, country_id) values ('Rokietnica', 9);
insert into city (name, country_id) values ('Casa Nova', 8);
insert into city (name, country_id) values ('Wailolong', 4);
insert into city (name, country_id) values ('Vallehermoso', 17);
insert into city (name, country_id) values ('Talodi', 5);
insert into city (name, country_id) values ('Uitiuhtuan', 20);
insert into city (name, country_id) values ('Leiden', 15);
insert into city (name, country_id) values ('Camalote', 6);
insert into city (name, country_id) values ('Studzienice', 2);
insert into city (name, country_id) values ('Ambohitrolomahitsy', 13);
insert into city (name, country_id) values ('Cuamba', 16);
insert into city (name, country_id) values ('Bantog', 16);
insert into city (name, country_id) values ('Muara', 8);
insert into city (name, country_id) values ('Sollebrunn', 13);
insert into city (name, country_id) values ('Kowingir', 11);
insert into city (name, country_id) values ('Baruunturuun', 7);
insert into city (name, country_id) values ('Basiao', 1);
insert into city (name, country_id) values ('Kairouan', 11);
insert into city (name, country_id) values ('Ōta', 3);
insert into city (name, country_id) values ('Livingstone', 19);
insert into city (name, country_id) values ('Kalyny', 13);
insert into city (name, country_id) values ('Novoye Devyatkino', 16);
insert into city (name, country_id) values ('Twardogóra', 6);
insert into city (name, country_id) values ('Iguatu', 5);
